CREATE TABLE IF NOT EXISTS Hacker_news(
    NEWS_NAME TEXT,
    RATINGS REAL,
    CHANEL_NAME TEXT
);

INSERT INTO Hacker_news(NEWS_NAME,RATINGS,CHANEL_NAME) VALUES
    ('HACKER SPOTTED IN CITY',70.38,'Newsch1'),
    ('NEW HACKER TODAY',71.40,'Newsch2'),
    ('KEEP YOU COMPUTER SAFE, HACKER INCOMING!',60.89,'Newsch3'),
    ('HACKER IN TOWN',69.67,'Newsch1'),
    ('IMPORTANT NEWS ABOUT HACKER',90.87,'Newsch2'),
    ('HACKER IN CITY',70.09,'Newsch2'),
    ('WATCHOUT FOR HACKERS',89.89,'Newsch3'),
    ('NEWS HACKER IN TOWN',67.29,'Newsch1');

SELECT NEWS_NAME AS 'News',RATINGS 
FROM Hacker_news
ORDER BY RATINGS DESC;